name: Verilate
on:
  push:
  workflow_dispatch:
jobs:
  verilator-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get HEAD Commit
        id: get-verilator-head
        run: |
          REVISION=$(git ls-remote https://github.com/verilator/verilator HEAD | awk '{ print $1 }')
          echo "Verilator HEAD: $REVISION"
          echo "commit=$REVISION" >> "$GITHUB_OUTPUT"

      - name: Cache the Verilator Build
        id: cache-verilator-build
        uses: actions/cache@v3
        with:
          key: verilator-${{ runner.os }}-${{ steps.get-verilator-head.outputs.commit }}
          path: ~/verilator.tgz

      # Based on the instructions <https://verilator.org/guide/latest/install.html#git-install>.
      - name: Checkout Sources
        uses: actions/checkout@v3
        if: ${{ steps.cache-verilator-build.outputs.cache-hit != 'true' }}
        with:
          repository: 'verilator/verilator'

      - name: Install Build Dependencies
        if: ${{ steps.cache-verilator-build.outputs.cache-hit != 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y git perl python3 make autoconf g++ flex bison ccache
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y libgoogle-perftools-dev numactl perl-doc
          sudo apt-get install -y libfl2  # Ubuntu only (ignore if gives error)
          sudo apt-get install -y libfl-dev  # Ubuntu only (ignore if gives error)
          sudo apt-get install -y help2man
          #sudo apt-get install -y zlibc zlib1g zlib1g-dev  # Ubuntu only (ignore if gives error)

      - name: Configure
        if: ${{ steps.cache-verilator-build.outputs.cache-hit != 'true' }}
        run: |
          unset VERILATOR_ROOT
          autoconf    # Create ./configure script
          ./configure # Configure and create Makefile

      - name: Build
        if: ${{ steps.cache-verilator-build.outputs.cache-hit != 'true' }}
        run: |
          make

      - name: Test
        if: ${{ steps.cache-verilator-build.outputs.cache-hit != 'true' }}
        run: |
          make test

      - name: Tar the build
        if: ${{ steps.cache-verilator-build.outputs.cache-hit != 'true' }}
        working-directory: ${{ github.workspace }}
        run: |
          DIR=$(mktemp -d)
          mkdir "$DIR/verilator"
          rsync -a --exclude='.*' . "$DIR/verilator"
          cd "$DIR"
          tar --posix -c -z -f ~/verilator.tgz verilator

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: verilator.tgz
          path: ~/verilator.tgz

  verilate:
    needs: verilator-build
    runs-on: ubuntu-latest
    steps:
      - name: Download verilator
        uses: actions/download-artifact@v3
        with:
          name: verilator.tgz

      - name: Untar Verilator
        run: |
          tar xzvf verilator.tgz

      - name: Install Verilator
        run: |
          sudo make -C verilator install

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'True'

      - name: Create Build Environment
        run: cmake -E make_directory "${{ runner.workspace }}/build"

      - name: Configure
        run: |
          cmake -G Ninja -B "${{ runner.workspace }}/build" -S "$GITHUB_WORKSPACE/verilator"

      - name: Build
        run: |
          cmake --build "${{ runner.workspace }}/build"

      - name: Run Tests
        run: |
          for f in $(find "${{ runner.workspace }}/build" -name CMakeFiles -prune -or -perm /u+x -type f -print); do
            echo $F
            $f
          done
